tests: Fix compiler warning on new clang
tests/regression/issue_838/enum_to_string.cxx:12:38:
    error: integer value 9999 is outside the valid range of values [0, 511]
    for this enumeration type [-Werror,-Wenum-constexpr-conversion]